### ISSUE TITLE
Bookmarks doesn't load the correct site

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1001]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Bookmarks doesn't load the correct site

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+ (iOS 10.3.3)

- Brave Version:
1.4 (1707.27.15)

- Steps to reproduce:
    1. Clean install beta build
    2. Open a site in new tab, add it as bookmark
    3. Open 3-4 tabs and visit sites and add bookmarks
    4. Without closing or opening a new tab, tap on each of the bookmarks added in previous steps
    5. Each bookmark loads a different site and then shows different title and favicon, going into edit mode shows a different site inside

- Actual Behavior
Bookmarks doesn't load the correct site

- Expected Behavior
Should load the correct bookmarked site

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
I was able to reproduce this twice on clean install of the beta build

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by jhreis** [comment]
Fixed per: 72c74290c9f4abc3f02f63a25b4ad712c7d033b5

**Comment by srirambv** [comment]
Still seeing this issue on 1.4(17.08.01.15) 
STR
1. Clean install the latest beta build
2. Tap on top tile and add as bookmark
3. Open new tab, load a different tile and add as bookmark
4. Repeat for all the tiles on newtab
5. After the last tile is added as bookmark, on the same tab open different bookmark in quick succession
6. Notice the Bookmark name is different and the page that loads is different

**Comment by jhreis** [comment]
Same internal issue as: https://github.com/brave/browser-ios/issues/1021. Related to CD merge conflicts not resolving correctly and blocking table updating.

**Comment by srirambv** [comment]
Should be fixed by 71539a8
