### ISSUE TITLE
Some elements on some sites not working (Buttons, Menus etc)

### ISSUE THREAD

**Issue by kunalverma25** [brave/browser-ios#1065]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Some buttons or sites elements not working on Brave.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6, IPad 2, Simulators (all)

- Brave Version:
1.4 (17.08.08.08, AppStore)

- Steps to reproduce:
    1. Go to waitrose.com
    2. Let the page load completely
    3. Try clicking the top right "Sign in/ Register Button" or the trolley icon keeps spinning
    4. Try clicking the top left menu button

- Actual Behavior
Nothing Happens

- Expected Behavior
If clicked on "Sign in/Register", browser should go to the sign in page.
If trolley icon shown, trolley loads after a couple seconds.
If clicked on trolley, browser should go to the trolley page
If clicked on menu icon, the dropdown menu should open.

- Is this an issue with Beta build?
N/A

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
Yes
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 
Yes, works on firefox iOS

- Screenshot if needed:

- Any related issues:
Same issues with some elements other sites as well. Eg tesco.com

**Comment by jhreis** [comment]
@kunalverma25 Thanks bunches for reporting this. It should be fixed in the next release. Really appreciate you taking the time to report this!

**Comment by kunalverma25** [comment]
@jhreis @jamesmudgett 
The issue is still there in the latest 1.4.1 beta release and with the '833d98f' commit as well.

I've actually found out the issue with the bug.
It's due to the "LoginsHelper" WKUserScript.
When injectIntoMain() is called from loadingCompleted() function.
If I remove that script from loading, then the websites work perfectly and as intended.
So please can you re-open this bug for further inspection.

**Comment by srirambv** [comment]
The menu dropdown works only when HTTPSE is disabled.  Remaining tests works.
