### ISSUE TITLE
intermittent odd tab bar scroll effect

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1120]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Sometimes the tab bar has an odd effect when scrolling.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad

- Brave Version:
1.4.1 (17.08.24.14)

- Steps to reproduce:
    1. Have several tabs, use your finger to swipe left and right to scroll through the tabs.
    2.
    3.

- Actual Behavior
Odd effect is displayed.

- Expected Behavior
No effect.

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
haven't seen it there yet.

- Can this issue be consistently reproduced?
No - currently intermittent.

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:
Look at the right side of the tab bar, about 1/3 of the way towards the middle to see the effect:
![tabbar](https://user-images.githubusercontent.com/28145373/29688814-f67e1f9c-88ee-11e7-9b87-3d25dd89b696.gif)

- Any related issues:

**Comment by LaurenWags** [comment]
Experienced this again using 1.4.2 (17.09.07.20) on iPad using iOS10 (10.3.1)

![img_0076](https://user-images.githubusercontent.com/28145373/30226189-1c615192-94a3-11e7-99cb-44d6dbc96ac6.PNG)

**Comment by jamesmudgett** [comment]
Fixed on latest 1.4.3 beta/1.5, QA please.

**Comment by srirambv** [comment]
This still happens on 1.4.3 beta
STR
1. Kill the app from  background
2. Open enough tabs to fill the tabs bar
3. Open any of the site in a new tab
4. Tap on the shields menu, has a weird overlay effect of shields
5. Close shields menu, the ghost image on tabs bar is still seen
6. Scroll left/right, the ghost effect moves towards the right of the tabs bar

**Comment by srirambv** [comment]
Still seeing this on 1.5. Able to reproduce with steps mentioned in https://github.com/brave/browser-ios/issues/1120#issuecomment-329694038

**Comment by LaurenWags** [comment]
Also able to reproduce using this STR with 1.5 (17.11.03.09)
Open 4 sites in 4 tabs, make first tab on the far left) the active tab.
Tap on bookmark icon, tap on gear to display Settings
Close settings, collapse left menu
Look at tab bar and see odd display in tab bar:
![img_0096](https://user-images.githubusercontent.com/28145373/32393715-05c4826c-c0b1-11e7-9929-173b78c4e8a9.PNG)
