### ISSUE TITLE
Stats counter get reset when app is removed from memory after clearing private data

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1240]
# Test plan
    1. Clean install or upgrade to beta
    2. Visit sites so that stats counter has values
    3. Remove app from memory, relaunch after a delay of 10 sec, all stats are still show
    4. Clear private data, new tab still shows the stats counter
    5. Remove the app from memory, relaunch after a delay of 10 sec, ensure stats are not reset
# 
### Description:
Stats counter get reset when app is removed from memory after clearing private data

### Steps to Reproduce

  1. Clean install or upgrade to beta
  2. Visit sites so that stats counter has values
  3. Remove app from memory, relaunch after a delay of 10 sec, all stats are still show
  4. Clear private data, new tab still shows the stats counter
  5. Remove the app from memory, relaunch after a delay of 10 sec, all stats are reset

**Actual result:**

Stats counter get reset when app is removed from memory after clearing private data

**Expected result:**
Stats should not clear when private data is cleared

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version:
1.5(17.10.13.15)
### Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone (iOS 10.3.3, iOS 11)
### Is this an issue in the currently released version?
No

### Website problems only: 
- did you check with Brave Shields down? N/A

- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?

**Comment by jamesmudgett** [comment]
fixed with ef7a67b4b72ee9868a01a0a5469e2ddefa29841a

**Comment by srirambv** [comment]
This is still reproducible in 1.5(17.10.26.08)
[1240.zip](https://github.com/brave/browser-ios/files/1419116/1240.zip)
