### ISSUE TITLE
Multiple bookmarks created when trying to remove bookmark 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#451]
Description:
Multiple bookmarks created when trying to remove bookmark 

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should create only one bookmark entry 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6(iOS 10)

- Brave Version:
1.2.16 Beta

- Steps to reproduce:
    1. Create a bookmark
    2. Slide the bookmark and tap on edit
    3. Go back to bookmark settings and tap on remove bookmark
    4. Might take couple of taps but continuously tapping on add bookmarks adds a second bookmark of the same page instead of removing it
    5. Tap again on remove bookmark removes both the entries

** Website problems only: N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A

- Screenshot if needed:
![1 convert-video-online com](https://cloud.githubusercontent.com/assets/17010094/18767098/35eae846-8115-11e6-943b-c820dfb4668b.gif)

- Any related issues:

**Comment by diegodoval** [comment]
fixed on PR https://github.com/brave/browser-ios/pull/454

**Comment by srirambv** [comment]
Reopening this issue. 

1. Create a bookmark 
2. Move the bookmark to a folder immediatley after creation
3. Go back to root folder and tap on bookmark icon, will create a new bookmark in root folder along with the one created in step 1 (inside folder)
4. At root folder tap on remove bookmark, both bookmarks are deleted 

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/17010094/19015697/1934de6c-8801-11e6-86ff-6c2945667109.gif)

**Comment by srirambv** [comment]
This is still an issue with 0.12.18 as well. Adding a bookmark and moving it into a folder and then adding a bookmark immediately moves the bookmark from the folder back to main view.
