### ISSUE TITLE
Wrong favicons shown on top site tiles

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#737]
Description: 
Wrong favicons shown on top site tiles

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Each site should show the sites favicon on the respective tile

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6(iOS 10)

- Brave Version:
1.3.1

- Steps to reproduce:
    1. Visit enough sites so that the top tiles are different from the default ones
    2. Enable Private browsing only or open a private tab in background the app for a long time
    3. Top tiles favicons are mixed up 
Seen this only on private tabs. 

** Website problems only: N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/23354774/9a21c718-fcca-11e6-8bb9-0a8347f8e2a3.png)
![image](https://cloud.githubusercontent.com/assets/17010094/23354837/dbc0e46a-fcca-11e6-84b4-ab4d556a38be.png)

- Any related issues:
cc: @garvankeeley @jhreis

**Comment by garvankeeley** [comment]
I can look as part of the CoreData hookup I am doing

**Comment by jhreis** [comment]
This is probably related to cell reuse.

**Comment by jhreis** [comment]
This should have been fixed via the huge CD migration as well as cell changes throughout.

**Comment by srirambv** [comment]
Issue still not fixed. Able to see same favicon and same tile name 
![image](https://cloud.githubusercontent.com/assets/17010094/25233070/6db55486-25d5-11e7-9c37-8bbf9d1f6385.png)

**Comment by jhreis** [comment]
Community bump. (https://community.brave.com/t/freudian-favicon-bug/4091/3)

Notice specification of the *title* being _correct_ and the *icon* being _incorrect_

**Comment by srirambv** [comment]
On latest 1.5 beta 
![image](https://user-images.githubusercontent.com/17010094/30840883-5ebdcece-a297-11e7-96c7-7dc03aed78b7.png)
